name: Build the documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build docs (Python ${{ matrix.python-version }}, Windows)
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Install Pandoc
        run: |
          choco install pandoc

      - name: Add Poetry to PATH
        run: |
          echo "$env:APPDATA\Python\Python39\Scripts" >> $env:GITHUB_PATH

      - name: Build the documentation with Sphinx
        run: |
          poetry install --all-extras
          poetry run sphinx-build -b html source build/html
        shell: cmd
